# Gather facts for all nodes
- hosts: all
  remote_user: kitchen
  sudo: yes

- hosts: frontend
  remote_user: kitchen
  sudo: yes
  roles:
  - frontend

- hosts: backend
  remote_user: kitchen
  sudo: yes
  roles:
  - backend

# Validate by a curl
- hosts: localhost
  tasks:
    - uri: url=http://web
