---

- apt: name=php5-fpm state=present
- lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp='^listen =' line='listen = 9000'
# Shared code between front and backend
- service: name=php5-fpm state=restarted
